# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(null=True)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(choices=[(b'1', b'Male'), (b'2', b'Female'), (b'3', b'Other')], max_length=2, null=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('activation_key', models.CharField(blank=b'True', max_length=40)),
                ('reset_password_key', models.CharField(blank=b'True', max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.datetime(2016, 3, 9, 12, 49, 40, 882192))),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='tmp_user_set', related_query_name=b'user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='tmp_user_set', related_query_name=b'user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'bloguser',
            },
        ),
        migrations.CreateModel(
            name='Blogcomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_name', models.CharField(max_length=100)),
                ('comment_date', models.DateTimeField(verbose_name=b'date commented')),
            ],
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_text', models.CharField(max_length=500)),
                ('author_name', models.CharField(max_length=100)),
                ('posted_date', models.DateTimeField(verbose_name=b'date posted')),
            ],
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newblogapp.Blogpost'),
        ),
    ]
